// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGFjFASG-hXwTV-S7AIjyzMUsreJmRnpE',
    appId: '1:82151791391:web:afc7c699437999ff2fae2a',
    messagingSenderId: '82151791391',
    projectId: 'malasackit-donation-app',
    authDomain: 'malasackit-donation-app.firebaseapp.com',
    storageBucket: 'malasackit-donation-app.firebasestorage.app',
    measurementId: 'G-XNFJNX6F0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvzL7eoPZgaonXpzRZKrhtQ2RjyYAtC04',
    appId: '1:82151791391:android:a8c4b3900d5a33932fae2a',
    messagingSenderId: '82151791391',
    projectId: 'malasackit-donation-app',
    storageBucket: 'malasackit-donation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFjKGivf90OT2YhzB5AylqXuVttEwFxgw',
    appId: '1:82151791391:ios:ed86c820c32791c32fae2a',
    messagingSenderId: '82151791391',
    projectId: 'malasackit-donation-app',
    storageBucket: 'malasackit-donation-app.firebasestorage.app',
    iosBundleId: 'com.example.donationAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFjKGivf90OT2YhzB5AylqXuVttEwFxgw',
    appId: '1:82151791391:ios:ed86c820c32791c32fae2a',
    messagingSenderId: '82151791391',
    projectId: 'malasackit-donation-app',
    storageBucket: 'malasackit-donation-app.firebasestorage.app',
    iosBundleId: 'com.example.donationAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGFjFASG-hXwTV-S7AIjyzMUsreJmRnpE',
    appId: '1:82151791391:web:3f6ac925c37280142fae2a',
    messagingSenderId: '82151791391',
    projectId: 'malasackit-donation-app',
    authDomain: 'malasackit-donation-app.firebaseapp.com',
    storageBucket: 'malasackit-donation-app.firebasestorage.app',
    measurementId: 'G-W72SE63JK7',
  );
}
